# Generated by Django 3.1.2 on 2020-10-29 06:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('objectid', models.BigIntegerField()),
                ('ido_lama', models.CharField(max_length=225)),
                ('ido_stltm', models.BigIntegerField()),
                ('ido_stltr', models.BigIntegerField()),
                ('ido_kwh', models.BigIntegerField()),
                ('ido_kvarh', models.BigIntegerField()),
                ('ido_kvam', models.BigIntegerField()),
                ('ido_mcb', models.BigIntegerField()),
                ('ido_timesw', models.BigIntegerField()),
                ('ido_kotaka', models.BigIntegerField()),
                ('ido_tiang', models.BigIntegerField()),
                ('ido_jurusa', models.BigIntegerField()),
                ('ido_feeder', models.BigIntegerField()),
                ('jenis_pela', models.CharField(max_length=1)),
                ('id_pelangg', models.CharField(max_length=12)),
                ('ido_kwh_la', models.CharField(max_length=254)),
                ('ido_mcb_la', models.CharField(max_length=254)),
                ('ido_time_1', models.CharField(max_length=254)),
                ('ido_kota_1', models.CharField(max_length=254)),
                ('ido_juru_1', models.CharField(max_length=254)),
                ('ido_gardu', models.CharField(max_length=254)),
                ('ido_feed_1', models.CharField(max_length=254)),
                ('nokontrak', models.CharField(max_length=9)),
                ('penggunaan', models.CharField(max_length=30)),
                ('jenis_app', models.CharField(max_length=10)),
                ('letak_app', models.CharField(max_length=1)),
                ('cara_pengu', models.BigIntegerField()),
                ('merk_app', models.CharField(max_length=15)),
                ('type_app', models.CharField(max_length=15)),
                ('no_seri', models.CharField(max_length=15)),
                ('tahun_buat', models.BigIntegerField()),
                ('digit_angk', models.BigIntegerField()),
                ('desimal_an', models.BigIntegerField()),
                ('putaran_ap', models.CharField(max_length=20)),
                ('grounding', models.CharField(max_length=14)),
                ('segel_app', models.CharField(max_length=20)),
                ('fasa', models.IntegerField()),
                ('nama_ct', models.CharField(max_length=30)),
                ('nama_pt', models.CharField(max_length=30)),
                ('nama_time', models.CharField(max_length=50)),
                ('merk_ct', models.CharField(max_length=15)),
                ('merk_pt', models.CharField(max_length=15)),
                ('merk_time', models.CharField(max_length=15)),
                ('no_seri_ct', models.CharField(max_length=15)),
                ('no_seri_pt', models.CharField(max_length=15)),
                ('no_seri_ti', models.CharField(max_length=15)),
                ('kelas_kete', models.BigIntegerField()),
                ('kelas_ke_1', models.BigIntegerField()),
                ('kelas_ke_2', models.BigIntegerField()),
                ('rasio_ct', models.BigIntegerField()),
                ('rasio_pt', models.BigIntegerField()),
                ('rasio_time', models.BigIntegerField()),
                ('nama_alat', models.CharField(max_length=30)),
                ('merk_pbts', models.CharField(max_length=15)),
                ('type_pbts', models.CharField(max_length=15)),
                ('no_seri_pb', models.CharField(max_length=15)),
                ('pembatas_d', models.BigIntegerField()),
                ('led_prabay', models.CharField(max_length=30)),
                ('catatan_kh', models.CharField(max_length=30)),
                ('jalan', models.CharField(max_length=50)),
                ('desa', models.CharField(max_length=50)),
                ('info_lingk', models.CharField(max_length=50)),
                ('kode_rayon', models.CharField(max_length=254)),
                ('kd_keduduk', models.CharField(max_length=15)),
                ('tarif', models.CharField(max_length=5)),
                ('daya', models.BigIntegerField()),
                ('catatan_1', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'pelanggan',
            },
        ),
    ]
