# Generated by Django 3.1.2 on 2020-10-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0002_auto_20201029_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='cara_pengu',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='catatan_1',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='catatan_kh',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='daya',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='desa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='desimal_an',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='digit_angk',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='fasa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='grounding',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='id_pelangg',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_feed_1',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_feeder',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_gardu',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_juru_1',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_jurusa',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_kota_1',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_kotaka',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_kvam',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_kvarh',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_kwh',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_kwh_la',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_lama',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_mcb',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_mcb_la',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_stltm',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_stltr',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_tiang',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_time_1',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='ido_timesw',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='info_lingk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='jalan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='jenis_app',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='jenis_pela',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='kd_keduduk',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='kelas_ke_1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='kelas_ke_2',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='kelas_kete',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='kode_rayon',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='led_prabay',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='letak_app',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='merk_app',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='merk_ct',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='merk_pbts',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='merk_pt',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='merk_time',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='nama_ct',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='nama_pt',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='no_seri',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='no_seri_ct',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='no_seri_pb',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='no_seri_pt',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='no_seri_ti',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='nokontrak',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='objectid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='pembatas_d',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='penggunaan',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='putaran_ap',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='rasio_ct',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='rasio_pt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='rasio_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='segel_app',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='tahun_buat',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='tarif',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='type_app',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggan',
            name='type_pbts',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
