# Generated by Django 3.1.2 on 2020-10-29 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0003_auto_20201029_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
