# from django.db import models
from django.contrib.gis.db import models

# Create your models here.
class Pelanggan(models.Model):
    # geom = models.PointField()
    objectid = models.BigIntegerField(null=True)
    ido_lama  = models.CharField(max_length=254, null=True)
    ido_stltm = models.BigIntegerField(null=True)
    ido_stltr = models.BigIntegerField(null=True)
    ido_kwh = models.BigIntegerField(null=True)
    ido_kvarh = models.BigIntegerField(null=True)
    ido_kvam = models.BigIntegerField(null=True)
    ido_mcb = models.BigIntegerField(null=True)
    ido_timesw = models.BigIntegerField(null=True)
    ido_kotaka = models.BigIntegerField(null=True)
    ido_tiang = models.BigIntegerField(null=True)
    ido_jurusa = models.BigIntegerField(null=True)
    ido_gardu = models.BigIntegerField(null=True)
    ido_feeder = models.BigIntegerField(null=True)
    jenis_pela  = models.CharField(max_length=1, null=True)
    id_pelangg  = models.CharField(max_length=12, null=True)
    ido_kwh_la  = models.CharField(max_length=254, null=True)
    ido_mcb_la  = models.CharField(max_length=254, null=True)
    ido_time_1  = models.CharField(max_length=254, null=True)
    ido_kota_1  = models.CharField(max_length=254, null=True)
    ido_juru_1  = models.CharField(max_length=254, null=True)
    ido_feed_1  = models.CharField(max_length=254, null=True)
    nokontrak  = models.CharField(max_length=9, null=True)
    penggunaan  = models.CharField(max_length=30, null=True)
    jenis_app  = models.CharField(max_length=30, null=True)
    letak_app  = models.CharField(max_length=1, null=True)
    cara_pengu = models.BigIntegerField(null=True)
    merk_app  = models.CharField(max_length=15, null=True)
    type_app  = models.CharField(max_length=15, null=True)
    no_seri  = models.CharField(max_length=15, null=True)
    tahun_buat = models.BigIntegerField(null=True)
    digit_angk = models.BigIntegerField(null=True)
    desimal_an = models.BigIntegerField(null=True)
    putaran_ap  = models.CharField(max_length=20, null=True)
    grounding  = models.CharField(max_length=14, null=True)
    segel_app  = models.CharField(max_length=20, null=True)
    fasa = models.IntegerField(null=True)
    nama_ct  = models.CharField(max_length=30, null=True)
    nama_pt  = models.CharField(max_length=30, null=True)
    merk_ct  = models.CharField(max_length=15, null=True)
    merk_pt  = models.CharField(max_length=15, null=True)
    merk_time  = models.CharField(max_length=15, null=True)
    no_seri_ct  = models.CharField(max_length=15, null=True)
    no_seri_pt  = models.CharField(max_length=15, null=True)
    no_seri_ti  = models.CharField(max_length=15, null=True)
    kelas_kete = models.BigIntegerField(null=True)
    kelas_ke_1 = models.BigIntegerField(null=True)
    kelas_ke_2 = models.BigIntegerField(null=True)
    rasio_ct = models.BigIntegerField(null=True)
    rasio_pt = models.BigIntegerField(null=True)
    rasio_time = models.BigIntegerField(null=True)
    merk_pbts  = models.CharField(max_length=15, null=True)
    type_pbts  = models.CharField(max_length=15, null=True)
    no_seri_pb  = models.CharField(max_length=15, null=True)
    pembatas_d = models.BigIntegerField(null=True)
    led_prabay  = models.CharField(max_length=30, null=True)
    catatan_kh  = models.CharField(max_length=30, null=True)
    jalan  = models.CharField(max_length=50, null=True)
    desa  = models.CharField(max_length=50, null=True)
    info_lingk  = models.CharField(max_length=50, null=True)
    kode_rayon  = models.CharField(max_length=5, null=True)
    kd_keduduk  = models.CharField(max_length=15, null=True)
    tarif  = models.CharField(max_length=5, null=True)
    daya = models.BigIntegerField(null=True)
    catatan_1  = models.CharField(max_length=254, null=True)

    create_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    def __str__(self):
        return "{}".format(self.id_pelangg)

    class Meta:
        db_table="pelanggan"